"""
Django settings for tutorial project.

Generated by 'django-admin startproject' using Django 2.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
from dotenv import load_dotenv


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

load_dotenv()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Provide a sane default so management commands can run during container builds where
# sensitive environment variables are not injected yet. Override via SECRET_KEY env var.
SECRET_KEY = os.getenv('SECRET_KEY') or 'sqlution-insecure-placeholder'



# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG_MODE', 'False').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = [host.strip() for host in os.getenv(
    'DJANGO_ALLOWED_HOSTS',
    'www.sqlution.de,sqlution.de,127.0.0.1,localhost'
).split(',') if host.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myapp',
    'rest_framework',  # Add Django Rest Framework
    'form_designer',
    'admin_ordering',
    'session_security',
    'axes',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'myapp.middleware.UserAgentMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'session_security.middleware.SessionSecurityMiddleware',
    'axes.middleware.AxesMiddleware',
]

AUTHENTICATION_BACKENDS = [
    # AxesStandaloneBackend should be the first backend in the AUTHENTICATION_BACKENDS list.
    'axes.backends.AxesStandaloneBackend',

    # Django ModelBackend is the default authentication backend.
    'django.contrib.auth.backends.ModelBackend',
]

ROOT_URLCONF = 'tutorial.urls'

TEMPLATE_CONTEXT_PROECESSORS = [
    'django.core.context_processors.request'
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tutorial.wsgi.application'

# trust all ALLOWED_HOSTS for CSRF
CSRF_TRUSTED_ORIGINS = []
CSRF_TRUSTED_ORIGINS += [f"https://{host}" for host in ALLOWED_HOSTS]




# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

SQLUTION_DB_PATH = os.getenv('SQLUTION_DB_PATH')
if not SQLUTION_DB_PATH:
    db_dir = os.getenv('SQLUTION_DB_DIR')
    if db_dir:
        SQLUTION_DB_PATH = os.path.join(db_dir, 'db.sqlite3')
    else:
        SQLUTION_DB_PATH = os.path.join(BASE_DIR, 'db.sqlite3')

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': SQLUTION_DB_PATH,
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'de-de'

TIME_ZONE = 'Europe/Berlin'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = os.getenv('DJANGO_STATIC_URL', '/app-static/').rstrip('/') + '/'

STATIC_ROOT = os.getenv('DJANGO_STATIC_ROOT', os.path.join(BASE_DIR, 'app-static'))

# Include shared project assets and generated frontend bundles during collectstatic.
STATICFILES_DIRS = [
    path for path in (
        os.path.join(BASE_DIR, 'static'),
        os.path.join(BASE_DIR, 'myapp/staticfiles'),
    ) if os.path.isdir(path)
]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

LOGIN_REDIRECT_URL = '/logged_in/'

LOGOUT_REDIRECT_URL = '/logged_out/'

SESSION_SECURITY_REDIRECT_TO_LOGOUT = False

SESSION_EXPIRE_AT_BROWSER_CLOSE = True

SECURE_CONTENT_NOSNIFF = False


SESSION_SECURITY_WARN_AFTER = 1740

SESSION_SECURITY_EXPIRE_AFTER  = 1800

SESSION_COOKIE_AGE = 1800

RESOURCES_REFRESH = 500

# File upload limits (bytes). Configure via env vars if needed.
# Increase these to allow larger uploads (default here: 100 MB).
FILE_UPLOAD_MAX_MEMORY_SIZE = int(os.getenv('FILE_UPLOAD_MAX_MEMORY_SIZE', 100 * 1024 * 1024))
# File permission for uploaded files on disk
FILE_UPLOAD_PERMISSIONS = 0o644

# Log Rotation Settings
LOG_ROTATION_MAX_SIZE_MB = 10  # Maximum log file size in MB before rotation
LOG_ROTATION_MAX_FILES = 4     # Maximum number of old log files to keep

AXES_FAILURE_LIMIT = 10

AXES_COOLOFF_TIME = 2