# Generated by Django 5.2 on 2025-04-15 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_databasemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databasemodel',
            name='db',
        ),
        migrations.RemoveField(
            model_name='databasemodel',
            name='json',
        ),
        migrations.RemoveField(
            model_name='databasemodel',
            name='sql',
        ),
        migrations.RemoveField(
            model_name='databasemodel',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='databasemodel',
            name='user',
        ),
    ]
