# Generated by Django 5.2 on 2025-04-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_databasemodel_db_remove_databasemodel_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasemodel',
            name='db',
            field=models.BinaryField(blank=True, default=b'', null=True),
        ),
        migrations.AddField(
            model_name='databasemodel',
            name='json',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='databasemodel',
            name='sql',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='databasemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='databasemodel',
            name='user',
            field=models.CharField(default='anonymous'),
        ),
    ]
