# Generated by Django 5.2 on 2025-04-15 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_databasemodel_db_databasemodel_json_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DatabaseModel',
        ),
    ]
