# Generated by Django 5.2 on 2025-04-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_delete_databasemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='anonymous')),
                ('json', models.JSONField(blank=True, default=dict, null=True)),
                ('sql', models.CharField(default='')),
                ('db', models.BinaryField(blank=True, default=b'', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
