# Generated by Django 5.2 on 2025-04-15 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_databasemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databasemodel',
            name='user',
        ),
    ]
