# Generated by Django 5.2 on 2025-04-15 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_databasemodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databasemodel',
            name='db',
        ),
    ]
