# Generated by Django 5.2 on 2025-04-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_databasemodel_db'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databasemodel',
            name='id',
        ),
        migrations.AddField(
            model_name='databasemodel',
            name='db',
            field=models.BinaryField(blank=True, default=b'', null=True),
        ),
        migrations.AddField(
            model_name='databasemodel',
            name='user',
            field=models.CharField(default='anonymous', primary_key=True, serialize=False),
        ),
    ]
