# Generated by Django 5.2 on 2025-04-15 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_databasemodel_id_databasemodel_db_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databasemodel',
            name='db',
        ),
    ]
