# Generated by Django 5.2 on 2025-04-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_databasemodel_db'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoItem',
        ),
        migrations.AlterField(
            model_name='databasemodel',
            name='sql',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='databasemodel',
            name='user',
            field=models.TextField(default='anonymous', primary_key=True, serialize=False),
        ),
    ]
