# Generated by Django 5.2 on 2025-04-16 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_databasemodel_db'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databasemodel',
            name='updated_at',
        ),
    ]
