# Generated by Django 5.2 on 2025-04-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_databasemodel_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
