# Generated by Django 5.2 on 2025-04-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_databasemodel_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databasemodel',
            name='updated_at',
            field=models.CharField(),
        ),
    ]
