# Generated by Django 5.2 on 2025-04-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_databasemodel_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZippedFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('zip_file', models.FileField(upload_to='zips/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
