# Generated by Django 5.2 on 2025-04-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_zippedfolder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zippedfolder',
            name='id',
        ),
        migrations.AlterField(
            model_name='zippedfolder',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
