# Generated by Django 5.2 on 2025-04-24 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_zippedfolder_id_alter_zippedfolder_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zippedfolder',
            name='created_at',
        ),
    ]
