# Generated by Django 5.2 on 2025-04-24 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_zippedfolder_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DatabaseModel',
        ),
    ]
