# Generated by Django 5.2 on 2025-05-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_zippedfolder_zip_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zippedfolder',
            name='zip_file',
            field=models.FileField(upload_to='zip/'),
        ),
    ]
