# Generated by Django 5.2 on 2025-07-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_auditlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='session_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
